-- LAUREN 50TH BIRTHDAY NOTES
-- Run this entire script in Supabase > SQL Editor.
-- Before running it, replace CHANGE_THIS_BIRTHDAY_PASSWORD with the shared
-- password you want guests to enter.

create extension if not exists pgcrypto;

create table if not exists public.birthday_notes (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 80),
  note text not null check (char_length(trim(note)) between 1 and 250),
  created_at timestamptz not null default now()
);

alter table public.birthday_notes enable row level security;

-- Remove broad browser permissions first.
revoke all on table public.birthday_notes from anon;
revoke all on table public.birthday_notes from authenticated;

-- Admin users signed into Supabase Auth may read notes.
grant select on table public.birthday_notes to authenticated;

drop policy if exists "Authenticated admin can read birthday notes" on public.birthday_notes;
create policy "Authenticated admin can read birthday notes"
on public.birthday_notes
for select
to authenticated
using (true);

-- Store only a salted bcrypt hash of the shared guest password.
create table if not exists public.birthday_settings (
  singleton boolean primary key default true check (singleton = true),
  password_hash text not null
);

alter table public.birthday_settings enable row level security;
revoke all on table public.birthday_settings from anon;
revoke all on table public.birthday_settings from authenticated;

insert into public.birthday_settings(singleton, password_hash)
values (true, crypt('WeLoveLauren', gen_salt('bf')))
on conflict (singleton) do update
set password_hash = excluded.password_hash;

-- Public submission function. Guests can call this, but cannot read the notes
-- or the stored password hash. SECURITY DEFINER is intentionally used so this
-- narrowly scoped function can insert despite the table being closed to anon.
create or replace function public.submit_birthday_note(
  p_password text,
  p_name text,
  p_note text
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_hash text;
begin
  select password_hash into v_hash
  from public.birthday_settings
  where singleton = true;

  if v_hash is null or crypt(p_password, v_hash) <> v_hash then
    raise exception 'Invalid birthday password';
  end if;

  if char_length(trim(p_name)) < 1 or char_length(trim(p_name)) > 80 then
    raise exception 'Name must be 1 to 80 characters';
  end if;

  if char_length(trim(p_note)) < 1 or char_length(trim(p_note)) > 250 then
    raise exception 'Note must be 1 to 250 characters';
  end if;

  insert into public.birthday_notes(name, note)
  values (trim(p_name), trim(p_note));
end;
$$;

revoke all on function public.submit_birthday_note(text,text,text) from public;
grant execute on function public.submit_birthday_note(text,text,text) to anon;
grant execute on function public.submit_birthday_note(text,text,text) to authenticated;
